apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  labels:
    app: busybox
    kind: VM
spec:
  template:
    metadata:
      name: busybox
      labels:
        app: busybox
        type: VM
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          args:
            - /bin/sh
            - -c
            - sleep 3600

  replicas: 3
  selector:
    matchLabels:
      type: VM