apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set
  labels:
    app: myreplicaset
    kind: frontend
spec:
  template:
    metadata:
      name: multi-pod
      labels:
        app: assignment1
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
        - name: redis
          image: redis
        - name: memcached
          image: memcached
  replicas: 5
  selector:
    matchLabels:
      type: frontend